### ISSUE TITLE
Bug fix for compound labels in plot_volcano function

### ISSUE THREAD

**Issue by delfarahalireza** [calico/claman#24]
The ```if``` ```else``` logic that I previously wrote to add ```compoundName``` to volcano plots has a bug since it seems like you can have only have one command within the ```if``` statement to add to ```ggplot```:

e.g. you can do:

``` 
df %>% ggplot(...) +
{if(...) {
geom_point(...)
}
}
``` 

but you cannot do: 

```
df %>% ggplot(...) +
{if(...) {
geom_point(...) +
geom_text
}
}
``` 

instead this would need to be:
```
df %>% ggplot(...) +
{if(...) {
geom_point(...)
}
} +
{if(...) {
geom_text(...)
}
}
```

**Comment by shackett** [comment]
> The `if` `else` logic that I previously wrote to add `compoundName` to volcano plots has a bug since it seems like you can have only have one command within the `if` statement to add to `ggplot`:
> 
> e.g. you can do:
> 
> ```
> df %>% ggplot(...) +
> {if(...) {
> geom_point(...)
> }
> }
> ```
> 
> but you cannot do:
> 
> ```
> df %>% ggplot(...) +
> {if(...) {
> geom_point(...) +
> geom_text
> }
> }
> ```
> 
> instead this would need to be:
> 
> ```
> df %>% ggplot(...) +
> {if(...) {
> geom_point(...)
> }
> } +
> {if(...) {
> geom_text(...)
> }
> }
> ```

Piping into an if statement isn't ideal. This isn't very readable. Its probably best to just assign the initial ggplot() call as a grob, and then build up the grob incrementally within if/else statements:

```{r}
grob <- ggplot(x, aes(...))

if ({true condition}) {
    grob <- grob + geom_xxx()
} else {
    grob <- grob + geom_xxx() + geom_yyy()
}

```

**Comment by delfarahalireza** [comment]
Thanks @shackett 

Committed changes per your suggestion here: https://github.com/calico/claman/pull/25
Can you please review?
